#Importing the database:

data <- read_csv("C:/Users/HP/Downloads/data.csv")

attach(data)

# Creating the columns to identify the eligible households for the matches of 50%, 20%, and 10% in 2020:

## source of the phase-out ranges in 2020: https://www.irs.gov/retirement-plans/plan-participant-employee/retirement-savings-contributions-savers-credit

### 50% match:

data['e_50'] <- case_when(((family_kind == 1) & (income <= 39000) & (marital_status == 1)) ~ 1,
                          ((family_kind == 2) & (income <= 29250) & (marital_status == 1)) ~ 1,
                          ((family_kind == 3) & (income <= 29250) & (marital_status == 1)) ~ 1,
                          ((income <= 19500) & (marital_status != 1)) ~ 1,
                          TRUE ~ 0
                          )

### 20% match:

data['e_20'] <- case_when(((family_kind == 1) & (income >= 39001) & (income <= 42500) & (marital_status == 1)) ~ 1,
                          ((family_kind == 2) & (income >= 29251) & (income <= 31875) & (marital_status == 1)) ~ 1,
                          ((family_kind == 3) & (income >= 29251) & (income <= 31875) & (marital_status == 1)) ~ 1,
                          ((income >= 19501) & (income <= 21250 ) & (marital_status != 1)) ~ 1,
                          TRUE ~ 0
                          )

### 10% match:

data['e_10'] <- case_when(((family_kind == 1) & (income >= 42501) & (income <= 65000) & (marital_status == 1)) ~ 1,
                          ((family_kind == 2) & (income >= 31876) & (income <= 48750) & (marital_status == 1)) ~ 1,
                          ((family_kind == 3) & (income >= 31876) & (income <= 48750) & (marital_status == 1)) ~ 1,
                          ((income >= 21251) & (income <= 32500 ) & (marital_status != 1)) ~ 1,
                          TRUE ~ 0
                         )

# Calculating the annual contribution in 2020:

data['abs_annual_contribution'] <- annual_contribution * income

# Calculating the credits generated by the Saver's Match Program:

data['credit'] <- case_when(((family_kind == 1) & (data$e_50 == 1) & ((data$abs_annual_contribution * 0.50) <= 5000) ~ (data$abs_annual_contribution * 0.50)), 
                            ((family_kind == 1) & (data$e_50 == 1) & ((data$abs_annual_contribution * 0.50) > 5000) ~ 5000),
                            ((family_kind != 1) & (data$e_50 == 1) & ((data$abs_annual_contribution * 0.50) <= 2500) ~ (data$abs_annual_contribution * 0.50)), 
                            ((family_kind != 1) & (data$e_50 == 1) & ((data$abs_annual_contribution * 0.50) > 2500) ~ 2500),
                            ((family_kind == 1) & (data$e_20 == 1) & ((data$abs_annual_contribution * 0.20) <= 5000) ~ (data$abs_annual_contribution * 0.20)), 
                            ((family_kind == 1) & (data$e_20 == 1) & ((data$abs_annual_contribution * 0.20) > 5000) ~ 5000),
                            ((family_kind != 1) & (data$e_20 == 1) & ((data$abs_annual_contribution * 0.20) <= 2500) ~ (data$abs_annual_contribution * 0.20)), 
                            ((family_kind != 1) & (data$e_20 == 1) & ((data$abs_annual_contribution * 0.20) > 2500) ~ 2500),
                            ((family_kind == 1) & (data$e_10 == 1) & ((data$abs_annual_contribution * 0.10) <= 5000) ~ (data$abs_annual_contribution * 0.10)), 
                            ((family_kind == 1) & (data$e_10 == 1) & ((data$abs_annual_contribution * 0.10) > 5000) ~ 5000),
                            ((family_kind != 1) & (data$e_10 == 1) & ((data$abs_annual_contribution * 0.10) <= 2500) ~ (data$abs_annual_contribution * 0.10)), 
                            ((family_kind != 1) & (data$e_10 == 1) & ((data$abs_annual_contribution * 0.10) > 2500) ~ 2500),
                            TRUE ~ 0
                            )
# Calculating the number of years to retire:

data['years_saving'] <- 65 - initial_age - 1

# Calculating accumulated_credit considering inflation of 4.4%:

data['credit_uptaded_init'] <- data$credit

data['accumulated_credit_init'] <- data$credit

func_accumulated <- function(credit_updated, accumulated_credit,years_savings){
                                                     num_range = years_savings
                          for (i in 1:years_savings) {credit_updated = credit_updated * 1.044
                                                      accumulated_credit = accumulated_credit + credit_updated}
                                                      return(list(accumulated_credit, credit_updated))}

accumulated_credit <- list()
  
  
for(i in 1:nrow(data)) { func <- func_accumulated(as.numeric(data[i,16]), as.numeric(data[i,17]), as.numeric(data[i,15]))
                       accumulated_credit <- append(accumulated_credit, func[1])
                       }

accumulated_credit_df <- as.data.frame(t(as.data.frame(accumulated_credit)))

data['accumulated_credit'] <- accumulated_credit_df$V1

# Calculating the column 'new_accumulated_capital':

data['new_accumulated_capital'] <- data$accumulated_capital + data$accumulated_credit

# Weighted Average Retirement Savings Shortfall by Race and Age Cohort:

## Creating cohorts by age:

data['cohorts'] <- case_when((initial_age >= 35) &  (initial_age <= 39) ~ '[35,39]',
                             (initial_age >= 40) &  (initial_age <= 44) ~ '[40,44]',
                             (initial_age >= 45) &  (initial_age <= 49) ~ '[45,49]',
                             (initial_age >= 50) &  (initial_age <= 54) ~ '[50,54]',
                             (initial_age >= 55) &  (initial_age <= 59) ~ '[55,59]',
                             (initial_age >= 60) &  (initial_age <= 64) ~ '[60,64]'
                             )

## Calculating the weighted accumulated capital:

data['weighted_accumulated_capital'] <- data$weight * data$new_accumulated_capital


## Calculating Retirement Savings Shortfall by race and age:

sum_weights <- data %>% group_by(cohorts, race) %>%
                       summarise(sum_weights = sum(weight))

sum_accumulated <- data %>% filter(new_accumulated_capital < 0) %>% 
                            group_by(cohorts, race) %>%
                           summarise(sum_accumulated = sum(new_accumulated_capital))

shortfall <- merge(sum_weights, sum_accumulated, on = c('cohorts', 'race'))

shortfall['rate'] <- shortfall$sum_accumulated / shortfall$sum_weights

shortfall['race'] <- as.character(shortfall$race)

shortfall['race'] <- gsub('1', 'White',
                     gsub('2', 'Black',
                     gsub('3','Hispanic',
                     gsub('4', 'Other',shortfall$race))))
  
## The plot(s):

### First plot:
ggplot(shortfall, aes(fill=race, y=cohorts, x=-rate)) + 
  geom_bar(position="dodge", stat="identity") +
  scale_fill_viridis(discrete = T, option = "E") +
  ggtitle("Weighted Average Retirement Savings Shortfall by Age and Race") +
  facet_wrap(~race) +
  theme_ipsum() +
  theme(legend.position="none", plot.title = element_text(hjust = 0.5, size = 15)) +
  xlab("") +
  ylab("")

### Second plot:

ggplot(shortfall, aes(fill=race, y=-rate, x=cohorts)) + 
  geom_bar(position="dodge", stat="identity") +
  scale_fill_viridis(discrete = T) +
  ggtitle("Weighted Average Retirement Savings Shortfall by Age and Race") +
  theme_ipsum() +
  theme(plot.title = element_text(hjust = 0.5, size = 15)) +
  xlab("") +
  ylab("")

# Calculating the Retirement Readiness Rating by age cohort:

sum_readiness_prev <- data %>% filter(accumulated_capital > 0) %>% 
  group_by(cohorts) %>%
  summarise(num_pos_prev = n())

sum_readiness_post <- data %>% filter(new_accumulated_capital > 0) %>% 
                      group_by(cohorts) %>%
                      summarise(num_pos_post = n())

readiness <- data %>% group_by(cohorts) %>%
                      summarise(tot = n()) %>%
                      left_join(sum_readiness_prev, by = c('cohorts')) %>%
                      left_join(sum_readiness_post, by = c('cohorts'))

readiness['rate_prev'] <- (readiness$num_pos_prev / readiness$tot)*100

readiness['rate_post'] <- (readiness$num_pos_post / readiness$tot)*100

readiness['impact'] <- readiness$rate_post - readiness$rate_prev


## Plot

ggplot(readiness, aes(y=impact, x=cohorts)) + 
  geom_bar(position="dodge", stat="identity", fill = '#66CCFF') +
  scale_fill_viridis(discrete = T) +
  ggtitle("Impact in the Retirement Readiness Rating by Age Cohort") +
  theme_ipsum() +
  theme(plot.title = element_text(hjust = 0.5, size = 15)) +
  xlab("") +
  ylab("") +
  geom_label(aes(label = round(impact,2)), colour = "black", size = 4, vjust = 1.0, fill = 'white')

#Exporting the database with new_accumulated_capital column:

write.csv(data, 'base_care_retirement', sep = ';', col.names = TRUE)



